wasmbus-rpc 0.7.0-alpha.1
wasmCloud/weld pull request #68
Opened 2022-01-10 04:53 UTC by stevelr

## wasmbus-rpc 0.7.0-alpha.1

- this is an "alpha" release so cargo won't automatically upgrade to this version unless it is specifically used as a dependency.

### Features

- replaced `ratsio` with `nats-aflowt`
  - `nats-aflowt` is reexported as `wasmbus_rpc::anats`
- removed dependency on nats-io/nats.rs (official nats client crate)
- `RpcClient::request` obeys the `timeout` parameter in `RpcClient::new(..)`

### Breaking changes (since 0.6.1)

- removed support for rpc_client types `Sync` and `Asynk`. Only `Async` now.
- `provider::NatsClient` changed type and is `anats::Connection`
- type `Subscription` is no longer exported (now: anats::Subscription)
- `HostBridge::new` - nats parameter no longer enclosed in Arc<>
- `get_async` returns `Option<anats::Connection>` instead of `Option<Arc<NatsClient>>`

2022-01-10 04:58 UTC, stevelr commented
All the testing I've done with this - and the underlying async nats library - passes. My plan is to publish this to crates.io with the -alpha tag, so that it is not automatically upgraded for most users, but it will enable broader testing.

2022-01-10 12:11 UTC, autodidaddict commented
Nats aflowt is full of warnings about not being ready and it also says it's unofficial. Does moving from ratsio to aflowt basically mean moving from one unsupported unofficial client to another?

2022-01-10 22:14 UTC, stevelr commented
> Nats aflowt is full of warnings about not being ready and it also says it's unofficial

I wrote those warnings, mostly to discourage others from using it before it had more testing. The main goal of this PR is to merge into main and publish the crate, to make it easier to do more testing and decide if it's ready.

2022-01-11 13:43 UTC, autodidaddict approved these changes

2022-01-11 15:18 UTC, brooksmtownsend requested changes
just one small request to hopefully avoid unfortunate error searching later

2022-01-11 15:18 UTC, brooksmtownsend commented on rpc-rs/src/provider_main.rs
> +const DEFAULT_NATS_ADDR: &str = "nats://0.0.0.0:4222";
this should be `nats://127.0.0.1:4222`

2022-01-11 23:41 UTC, brooksmtownsend approved these changes
LGTM

2022-01-13 01:09 UTC, merged